TABLES 
- 4-14
- 4-15
- 4-16

In [1]:
%load_ext autoreload
%matplotlib widget
%autoreload 2

import pandas as pd
import numpy  as np
pd.set_option("display.max_rows", None)

df_imperial = pd.read_csv("data_ACSR_imperial.csv")
df_metric   = df_imperial.copy()
#df_imperial

In [2]:
lb_1000ft_2_kg_km = (0.453592/0.0003048)/1000
inch2_2_mm2       = (2.54*10)**2
inch_2_mm         = 2.54*10
ohms_mi_2_ohms_km = 1/1.60934

df_metric['S_AL'] *= inch2_2_mm2
df_metric['S_T']  *= inch2_2_mm2

df_metric['d_AL'] *= inch_2_mm
df_metric['d_ST'] *= inch_2_mm
df_metric['D']    *= inch_2_mm
df_metric['D_c']  *= inch_2_mm

df_metric['W_T' ] *= lb_1000ft_2_kg_km 
df_metric['W_AL'] *= lb_1000ft_2_kg_km 
df_metric['W_ST'] *= lb_1000ft_2_kg_km 

df_metric['R25'] *= ohms_mi_2_ohms_km
df_metric['R50'] *= ohms_mi_2_ohms_km 
df_metric['R75'] *= ohms_mi_2_ohms_km 

# ROUND THE DATA
round_dict = {}
for i in [1,2,4,6,7,8,9,10,11]: round_dict[df_metric.columns[i]] = 2
for i in [12,13,14]:            round_dict[df_metric.columns[i]] = 5
df_metric = df_metric.round(round_dict)

df_metric

,Code,S_AL,S_T,n_AL,d_AL,n_ST,d_ST,D,D_c,W_T,W_AL,W_ST,R25,R50,R75
0,Turkey,13.29,15.48,6,1.68,1,1.68,5.03,1.68,53.57,36.31,17.26,NaN,NaN,NaN
1,Swan,21.16,24.71,6,2.12,1,2.12,6.35,2.12,85.42,58.04,27.38,NaN,NaN,NaN
2,Swanate,21.16,26.52,7,1.96,1,2.61,6.53,2.61,99.71,58.04,41.67,NaN,NaN,NaN
3,Sparrow,33.61,39.23,6,2.67,1,2.67,8.03,2.67,135.72,92.12,43.60,NaN,NaN,NaN
4,Sparate,33.61,42.13,7,2.47,1,3.30,8.25,3.30,151.79,92.71,66.52,NaN,NaN,NaN
5,Robin,42.39,49.48,6,3.00,1,3.00,9.02,3.00,171.14,116.23,54.91,NaN,NaN,NaN
6,Raven,53.48,62.39,6,3.37,1,3.37,10.11,3.37,215.78,146.44,69.35,NaN,NaN,NaN
7,Quall,67.42,78.65,6,3.78,1,3.78,11.35,3.78,272.33,184.83,87.50,NaN,NaN,NaN
8,Pigeon,85.03,99.23,6,4.25,1,4.25,12.75,4.25,342.28,232.00,110.27,NaN,NaN,NaN
9,LA125-Penguin,107.23,125.10,6,4.77,1,4.77,14.30,4.77,433.06,294.06,138.99,0.26968,0.34983,0.37966
10,Waxwing,135.16,142.64,18,3.09,1,3.09,15.47,3.09,430.08,371.74,58.34,NaN,NaN,NaN
11,Partridge,135.16,157.16,26,2.57,7,2.00,16.31,6.00,544.67,372.64,172.03,NaN,NaN,NaN
12,LA175-Ostrich,151.94,176.64,26,2.73,7,2.12,17.27,6.36,613.12,419.96,193.16,0.19014,0.20878,0.22742
13,Merlin,170.45,179.94,18,3.47,1,3.47,17.37,3.47,543.18,469.52,73.66,NaN,NaN,NaN
14,Linnet,170.32,198.06,26,2.89,7,2.25,18.29,6.74,687.53,471.00,216.53,NaN,NaN,NaN
15,Oriole,170.45,210.26,30,2.69,7,2.69,18.82,8.07,782.77,471.75,311.03,NaN,NaN,NaN
16,Chickadee,201.42,212.58,18,3.77,1,3.77,18.87,3.77,641.40,554.34,87.06,NaN,NaN,NaN
17,Ibis,201.29,234.06,26,3.14,7,2.44,19.89,7.32,812.54,556.72,255.82,NaN,NaN,NaN
18,Lark,201.35,248.32,30,2.92,7,2.92,20.47,8.77,925.64,558.21,367.43,NaN,NaN,NaN
19,Pelican,241.74,255.16,18,4.14,1,4.14,20.68,4.14,769.38,664.91,104.47,NaN,NaN,NaN
20,Flicker,241.74,273.10,24,3.58,7,2.39,21.49,7.16,913.73,668.93,244.80,NaN,NaN,NaN
21,LA280-Hawk,241.55,280.84,26,3.44,7,2.67,21.79,8.02,974.75,667.59,307.16,0.11992,0.13173,0.14354
22,Hen,241.74,298.13,30,3.20,7,3.20,22.43,9.61,1110.17,669.23,440.94,NaN,NaN,NaN
23,Osprey,281.87,298.13,18,4.47,1,4.47,22.33,4.47,897.36,775.48,121.88,NaN,NaN,NaN
24,Parakeet,282.06,318.58,24,3.87,7,2.58,23.22,7.73,1065.52,780.09,285.43,NaN,NaN,NaN
25,Dove,282.00,327.93,26,3.72,7,2.89,23.55,8.66,1138.44,779.65,358.80,NaN,NaN,NaN
26,Eagle,282.00,347.81,30,3.46,7,3.46,24.21,10.39,1296.19,778.76,514.46,NaN,NaN,NaN
27,Peacock,306.64,346.45,24,4.03,7,2.69,24.21,8.08,1159.28,848.55,310.73,NaN,NaN,NaN
28,Squab,306.39,356.26,26,3.87,7,3.01,24.54,9.04,1238.15,846.91,389.75,NaN,NaN,NaN
29,Teal,306.52,376.39,30,3.61,19,2.16,25.25,10.82,1397.38,850.48,546.90,NaN,NaN,NaN
30,Kingbird,322.39,340.32,18,4.78,1,4.78,23.88,4.78,1026.83,887.54,139.29,NaN,NaN,NaN
31,Rook,319.74,364.06,24,4.14,7,2.76,24.82,8.28,1217.32,891.11,326.21,NaN,NaN,NaN
32,Grosbeak,322.26,374.71,26,3.97,7,3.09,25.15,9.27,1299.17,890.96,409.69,NaN,NaN,NaN
33,Swift,322.19,331.16,36,3.38,1,3.38,23.62,3.38,956.89,886.94,69.94,NaN,NaN,NaN
34,Egret,322.26,395.81,30,3.70,19,2.22,25.88,11.10,1468.82,893.20,575.62,NaN,NaN,NaN
35,Flamingo,337.93,381.74,24,4.23,7,2.82,25.40,8.46,1276.84,934.86,341.98,NaN,NaN,NaN
36,Crow,362.58,409.48,54,2.92,7,2.92,26.42,8.76,1369.11,1003.02,366.09,NaN,NaN,NaN
37,Starling,362.58,421.61,26,4.21,7,3.28,26.70,9.83,1464.35,1003.32,461.03,NaN,NaN,NaN
38,Redwing,362.39,444.97,30,3.92,19,2.35,27.46,11.76,1650.37,1004.51,645.86,NaN,NaN,NaN
39,Coot,402.84,414.00,36,3.77,1,3.77,26.42,3.76,1196.48,1108.68,87.80,NaN,NaN,NaN
40,Cuckoo,402.84,455.03,24,4.62,7,3.08,27.74,9.25,1523.88,1116.12,407.76,NaN,NaN,NaN
41,Drake,403.03,468.64,26,4.44,7,3.45,28.14,10.36,1626.56,1114.63,511.93,0.07270,0.07954,0.08637
42,Mallard,402.90,494.77,30,4.14,19,2.48,28.96,12.42,1836.39,1117.61,718.78,NaN,NaN,NaN
43,Tern,402.71,430.58,45,3.38,7,2.25,27.00,6.76,1331.91,1114.49,217.42,NaN,NaN,NaN
44,LA455-Condor,402.58,454.77,54,3.08,7,3.08,27.74,9.25,1520.90,1113.15,407.76,0.07270,0.08016,0.08699
45,Crane,443.42,500.90,54,3.23,7,3.23,29.21,9.70,1675.67,1226.25,449.43,NaN,NaN,NaN
46,Ruddy,455.87,487.42,45,3.59,7,2.40,28.73,7.19,1507.51,1260.47,247.04,NaN,NaN,NaN
47,Canary,456.06,515.16,54,3.28,7,3.28,29.51,9.83,1723.29,1261.96,461.33,NaN,NaN,NaN
48,Corncrake,483.35,516.84,20,5.55,7,2.47,29.59,7.39,1598.29,1337.86,260.43,NaN,NaN,NaN
49,Rail,483.35,516.77,45,3.70,7,2.47,29.59,7.39,1599.77,1337.86,261.92,NaN,NaN,NaN
50,Towhee,483.48,526.19,48,3.58,7,2.79,29.84,8.36,1671.21,1337.86,333.35,NaN,NaN,NaN
51,Redbird,483.48,546.13,24,5.06,7,3.38,30.38,10.13,1827.46,1337.86,489.61,NaN,NaN,NaN
52,LA545-Cardinal,483.29,545.93,54,3.38,7,3.38,30.38,10.13,1827.46,1337.86,489.61,0.06108,0.06711,0.07270
53,Ortolan,523.35,559.55,45,3.85,7,2.57,30.78,7.70,1730.73,1447.98,282.75,NaN,NaN,NaN
54,Curlew,523.35,591.22,54,3.51,7,3.51,31.62,10.54,1977.77,1447.98,529.79,NaN,NaN,NaN
55,Bluejay,564.19,603.22,45,4.00,7,2.66,31.98,8.00,1866.16,1561.08,305.07,NaN,NaN,NaN
56,LA635-Finch,564.19,635.74,54,3.65,19,2.19,32.84,10.95,2128.07,1568.52,559.55,0.05288,0.05785,0.06276
57,Bunting,604.32,646.06,45,4.14,7,2.76,33.07,8.28,1997.11,1671.21,325.91,NaN,NaN,NaN
58,Grackle,604.19,680.77,54,3.77,19,2.27,33.99,11.33,2278.38,1678.65,599.73,NaN,NaN,NaN
59,Bittern,644.32,688.77,45,4.27,7,2.85,34.16,8.53,2131.05,1782.82,348.23,NaN,NaN,NaN
60,Pheasant,644.71,726.39,54,3.90,19,2.34,35.10,11.71,2431.66,1793.24,638.42,NaN,NaN,NaN
61,Dipper,684.77,732.13,45,4.40,7,2.93,35.20,8.81,2263.50,1894.43,369.06,NaN,NaN,NaN
62,Martin,684.77,771.48,54,4.02,19,2.41,36.17,12.06,2581.96,1903.36,678.60,NaN,NaN,NaN
63,Bobolink,724.84,774.97,45,4.53,7,3.02,36.25,9.07,2397.43,2006.04,391.39,NaN,NaN,NaN
64,Plover,725.16,817.03,54,4.14,19,2.48,37.21,12.42,2735.24,2016.46,718.78,NaN,NaN,NaN
65,Nuthatch,765.29,818.13,45,4.65,7,3.10,37.24,9.30,2529.88,2116.17,413.71,NaN,NaN,NaN
66,Parrot,764.90,861.74,54,4.25,19,2.55,38.23,12.75,2884.06,2126.58,757.47,NaN,NaN,NaN
67,Lapwing,805.93,861.61,45,4.78,7,3.18,38.20,9.55,2663.81,2229.27,434.54,NaN,NaN,NaN
68,Falcon,805.74,907.87,54,4.36,19,2.62,39.24,13.11,3038.83,2239.68,799.14,NaN,NaN,NaN
69,Chukar,902.32,975.61,84,3.70,19,2.22,40.69,11.10,3083.47,2507.55,575.92,NaN,NaN,NaN
70,Mockingbird,1030.90,1075.55,72,4.27,7,2.85,42.70,8.53,3218.90,2870.67,348.23,NaN,NaN,NaN
71,Bluebird,1092.32,1181.22,84,4.07,19,2.44,44.75,12.22,3732.31,3035.85,696.46,NaN,NaN,NaN
72,Kiwi,1098.19,1145.68,72,4.41,7,2.94,44.07,8.81,3422.77,3052.22,370.55,NaN,NaN,NaN
73,Thrasher,1171.29,1235.09,76,4.43,19,2.07,45.77,10.34,3754.63,3256.10,498.53,NaN,NaN,NaN
74,Jorea,1274.19,1343.74,76,4.62,19,2.16,47.75,10.80,4090.96,3547.78,543.18,NaN,NaN,NaN
75,Grouse,40.52,54.65,8,2.54,1,4.24,9.32,4.24,221.74,111.76,109.98,NaN,NaN,NaN
76,Petrel,51.61,81.68,12,2.34,7,2.34,11.71,7.02,377.99,142.71,235.28,NaN,NaN,NaN
77,Minorca,56.13,88.90,12,2.44,7,2.44,12.22,7.32,410.73,154.62,256.11,NaN,NaN,NaN
78,Leghorn,68.19,108.00,12,2.69,7,2.69,13.46,8.07,500.02,189.00,311.03,NaN,NaN,NaN
79,Guinea,80.58,127.55,12,2.92,7,2.92,14.63,8.77,589.31,221.89,367.43,NaN,NaN,NaN
80,Dotterel,89.61,141.94,12,3.08,7,3.08,15.42,9.25,656.28,247.63,408.65,NaN,NaN,NaN
81,Dorking,96.71,153.10,12,3.20,7,3.20,16.03,9.61,708.37,267.42,440.94,NaN,NaN,NaN
82,Brahma,103.10,194.84,16,2.86,19,2.48,18.14,12.41,930.10,282.60,721.91,NaN,NaN,NaN
83,Cochin,107.10,194.84,12,3.37,7,3.37,16.84,10.11,784.26,295.85,488.42,NaN,NaN,NaN

In [3]:
# conductor_code = "LA280-Hawk","Drake","LA455-Condor"
# df_metric[df_metric["Code"] == conductor_code]

rows      = [9,12,21,41,44,52,56]         
df_subset = df_metric.iloc[rows]
df_subset

,Code,S_AL,S_T,n_AL,d_AL,n_ST,d_ST,D,D_c,W_T,W_AL,W_ST,R25,R50,R75
9,LA125-Penguin,107.23,125.10,6,4.77,1,4.77,14.30,4.77,433.06,294.06,138.99,0.26968,0.34983,0.37966
12,LA175-Ostrich,151.94,176.64,26,2.73,7,2.12,17.27,6.36,613.12,419.96,193.16,0.19014,0.20878,0.22742
21,LA280-Hawk,241.55,280.84,26,3.44,7,2.67,21.79,8.02,974.75,667.59,307.16,0.11992,0.13173,0.14354
41,Drake,403.03,468.64,26,4.44,7,3.45,28.14,10.36,1626.56,1114.63,511.93,0.07270,0.07954,0.08637
44,LA455-Condor,402.58,454.77,54,3.08,7,3.08,27.74,9.25,1520.90,1113.15,407.76,0.07270,0.08016,0.08699
52,LA545-Cardinal,483.29,545.93,54,3.38,7,3.38,30.38,10.13,1827.46,1337.86,489.61,0.06108,0.06711,0.07270
56,LA635-Finch,564.19,635.74,54,3.65,19,2.19,32.84,10.95,2128.07,1568.52,559.55,0.05288,0.05785,0.06276