TABLES 
- 4-14
- 4-15
- 4-16

In [1]:
%load_ext autoreload
%matplotlib widget
%autoreload 2
import pandas as pd

df_metric = pd.read_csv("data_ACSR_metric.csv")
df_metric

,Code,S_AL,S_T,n_AL,d_AL,n_ST,d_ST,D,D_c,W_T,W_AL,W_ST,R25,R50,R75
0,Turkey,13.29,15.48,6,1.68,1,1.68,5.03,1.68,53.57,36.31,17.26,NaN,NaN,NaN
1,Swan,21.16,24.71,6,2.12,1,2.12,6.35,2.12,85.42,58.04,27.38,NaN,NaN,NaN
2,Swanate,21.16,26.52,7,1.96,1,2.61,6.53,2.61,99.71,58.04,41.67,NaN,NaN,NaN
3,Sparrow,33.61,39.23,6,2.67,1,2.67,8.03,2.67,135.72,92.12,43.60,NaN,NaN,NaN
4,Sparate,33.61,42.13,7,2.47,1,3.30,8.25,3.30,151.79,92.71,66.52,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Guinea,80.58,127.55,12,2.92,7,2.92,14.63,8.77,589.31,221.89,367.43,NaN,NaN,NaN
80,Dotterel,89.61,141.94,12,3.08,7,3.08,15.42,9.25,656.28,247.63,408.65,NaN,NaN,NaN
81,Dorking,96.71,153.10,12,3.20,7,3.20,16.03,9.61,708.37,267.42,440.94,NaN,NaN,NaN
82,Brahma,103.10,194.84,16,2.86,19,2.48,18.14,12.41,930.10,282.60,721.91,NaN,NaN,NaN
83,Cochin,107.10,194.84,12,3.37,7,3.37,16.84,10.11,784.26,295.85,488.42,NaN,NaN,NaN

In [5]:
# conductor_code = "LA280-Hawk","Drake","LA455-Condor"
# df_metric[df_metric["Code"] == conductor_code]
rows   = [9,12,21,41,44,52,56]         
df_app = df_metric.iloc[rows]
df_app

,Code,S_AL,S_T,n_AL,d_AL,n_ST,d_ST,D,D_c,W_T,W_AL,W_ST,R25,R50,R75
9,LA125-Penguin,107.23,125.10,6,4.77,1,4.77,14.30,4.77,433.06,294.06,138.99,0.26968,0.34983,0.37966
12,LA175-Ostrich,151.94,176.64,26,2.73,7,2.12,17.27,6.36,613.12,419.96,193.16,0.19014,0.20878,0.22742
21,LA280-Hawk,241.55,280.84,26,3.44,7,2.67,21.79,8.02,974.75,667.59,307.16,0.11992,0.13173,0.14354
41,Drake,403.03,468.64,26,4.44,7,3.45,28.14,10.36,1626.56,1114.63,511.93,0.07270,0.07954,0.08637
44,LA455-Condor,402.58,454.77,54,3.08,7,3.08,27.74,9.25,1520.90,1113.15,407.76,0.07270,0.08016,0.08699
52,LA545-Cardinal,483.29,545.93,54,3.38,7,3.38,30.38,10.13,1827.46,1337.86,489.61,0.06108,0.06711,0.07270
56,LA635-Finch,564.19,635.74,54,3.65,19,2.19,32.84,10.95,2128.07,1568.52,559.55,0.05288,0.05785,0.06276

In [7]:
df_app = df_app.set_index('Code')

# 3. Convert to JSON with orient='index'
json_output = df_app.to_json(orient='index')

# Printing the result to verify
print(json_output)

{"LA125-Penguin":{"S_AL":107.23,"S_T":125.1,"n_AL":6,"d_AL":4.77,"n_ST":1,"d_ST":4.77,"D":14.3,"D_c":4.77,"W_T":433.06,"W_AL":294.06,"W_ST":138.99,"R25":0.26968,"R50":0.34983,"R75":0.37966},"LA175-Ostrich":{"S_AL":151.94,"S_T":176.64,"n_AL":26,"d_AL":2.73,"n_ST":7,"d_ST":2.12,"D":17.27,"D_c":6.36,"W_T":613.12,"W_AL":419.96,"W_ST":193.16,"R25":0.19014,"R50":0.20878,"R75":0.22742},"LA280-Hawk":{"S_AL":241.55,"S_T":280.84,"n_AL":26,"d_AL":3.44,"n_ST":7,"d_ST":2.67,"D":21.79,"D_c":8.02,"W_T":974.75,"W_AL":667.59,"W_ST":307.16,"R25":0.11992,"R50":0.13173,"R75":0.14354},"Drake":{"S_AL":403.03,"S_T":468.64,"n_AL":26,"d_AL":4.44,"n_ST":7,"d_ST":3.45,"D":28.14,"D_c":10.36,"W_T":1626.56,"W_AL":1114.63,"W_ST":511.93,"R25":0.0727,"R50":0.07954,"R75":0.08637},"LA455-Condor":{"S_AL":402.58,"S_T":454.77,"n_AL":54,"d_AL":3.08,"n_ST":7,"d_ST":3.08,"D":27.74,"D_c":9.25,"W_T":1520.9,"W_AL":1113.15,"W_ST":407.76,"R25":0.0727,"R50":0.08016,"R75":0.08699},"LA545-Cardinal":{"S_AL":483.29,"S_T":545.93,"n_AL":54,"d_AL":3.38,"n_ST":7,"d_ST":3.38,"D":30.38,"D_c":10.13,"W_T":1827.46,"W_AL":1337.86,"W_ST":489.61,"R25":0.06108,"R50":0.06711,"R75":0.0727},"LA635-Finch":{"S_AL":564.19,"S_T":635.74,"n_AL":54,"d_AL":3.65,"n_ST":19,"d_ST":2.19,"D":32.84,"D_c":10.95,"W_T":2128.07,"W_AL":1568.52,"W_ST":559.55,"R25":0.05288,"R50":0.05785,"R75":0.06276}}